- name: Provision the AWS k3s instance
  hosts: localhost
  gather_facts: true
  tasks:
    - name: create ec2 instance
      include_tasks: tasks/ec2-create-instance.yml

- name: wait for SSH to come up
  hosts: running
  gather_facts: false
  tasks:
    - name: wait for ssh to come up
      wait_for_connection:
        delay: "{{ (hostvars['localhost']['instances_launched'].changed or hostvars['localhost']['instances'].changed) | ternary(60, 0) }}"
        timeout: 180

- name: configure instances
  hosts: running
  become: true
  gather_facts: true
  vars:
    - kubeconfig_path: '.kubeconfig/ec2.yaml'
  tasks:
    - name: install k3s
      include_tasks: tasks/install-k3s.yml

    - name: download the kubeconfig file.
      fetch:
        src: /etc/rancher/k3s/k3s.yaml
        dest: "{{ kubeconfig_path }}"
        flat: true

    - name: replace the ip address in kubeconfig
      replace:
        path: "{{ kubeconfig_path }}"
        regexp: '127.0.0.1'
        replace: "{{ public_dns_name }}"
      delegate_to: 127.0.0.1
      become: false

    - name: install k8s dashboard
      include_tasks: tasks/install-dashboard.yml

- name: disable ssh access
  hosts: localhost
  gather_facts: false
  tasks:
    - include_tasks: tasks/ec2-disable-ssh.yml
