- name: Provision the AWS k3s instance
  hosts: localhost
  gather_facts: False
  tasks:
    - name: get security groups
      amazon.aws.ec2_group_info:
        filters:
          group-name: k3s
      register: security_groups

    - name: create security group
      amazon.aws.ec2_group:
        name: k3s
        description: Rules for k3s
        rules:
          - proto: tcp
            ports:
            - 22
            cidr_ip: 0.0.0.0/0
            rule_desc: allow all on port 22
          - proto: tcp
            ports:
            - 80
            cidr_ip: 0.0.0.0/0
            rule_desc: allow all on port 80
          - proto: tcp
            ports:
            - 443
            cidr_ip: 0.0.0.0/0
            rule_desc: allow all on port 443
      when: security_groups.security_groups|length == 0

    - name: launch instance
      amazon.aws.ec2:
        group: k3s
        image: ami-07aa5ef6af56f8da2
        instance_tags:
          Name: k3s
        instance_type: t4g.micro
        key_name: yusufhm
        state: running
        termination_protection: true
        vpc_subnet_id: subnet-378add71
        wait: yes
