- name: Provision the AWS k3s instance
  hosts: localhost
  gather_facts: False
  tasks:
    - name: create ec2 instance
      include_tasks: tasks/ec2-create-instance.yml

- name: wait for SSH to come up
  hosts: running
  gather_facts: false
  tasks:
    - wait_for_connection:
        delay: "{{ (hostvars['localhost']['instances_launched'].changed or hostvars['localhost']['instances'].changed) | ternary(60, 0) }}"
        timeout: 180

- name: configure instances
  hosts: running
  become: yes
  gather_facts: true
  tasks:
    - name: install k3s
      include_tasks: tasks/install-k3s.yml

    - name: download the kubeconfig file.
      fetch:
        src: /etc/rancher/k3s/k3s.yaml
        dest: .kubeconfig/ec2.yaml
        flat: yes

    - name: replace the ip address in kubeconfig
      replace:
        path: .kubeconfig/ec2.yaml
        regexp: '127.0.0.1'
        replace: "{{ public_dns_name }}"
      delegate_to: 127.0.0.1
      become: false

- name: disable ssh access
  hosts: localhost
  gather_facts: False
  tasks:
    - include_tasks: tasks/ec2-disable-ssh.yml
