---
- hosts: all
  become: true
  vars:
    - dashboard_deploy_type: 'alternative'
    - kube_dashboard_enable_ingress: true
  tasks:
    - name: install k3s
      include_tasks: tasks/install-k3s.yml

    # Leaving this in even though we're using static IP, because the IP could
    # be changed in a Vagranfile.local.
    - name: get ip address
      shell: |
        set -o pipefail
        ip address show eth1 | grep 'inet ' | sed -e 's/^.*inet //' -e 's/\/.*$//'
      register: ip_result
      changed_when: true

    - name: download the kubeconfig file.
      fetch:
        src: /etc/rancher/k3s/k3s.yaml
        dest: .kubeconfig/localvm.yaml
        flat: true

    - name: replace the ip address in kubeconfig
      replace:
        path: .kubeconfig/localvm.yaml
        regexp: '127.0.0.1'
        replace: "{{ ip_result.stdout }}"
      delegate_to: 127.0.0.1
      become: false

    - name: install k8s dashboard
      include_tasks: tasks/install-dashboard.yml

    - name: install apps
      include_tasks: tasks/install-apps.yml
