---
- hosts: all
  become: yes
  tasks:
    - name: install nginx app
      kubernetes.core.k8s:
        kubeconfig: /etc/rancher/k3s/k3s.yaml
        state: present
        definition: "{{ item }}"
      loop: "{{ lookup('file', 'k8-configs/app.nginx.yml') | from_yaml_all | list }}"
