---
- hosts: all
  become: yes
  tasks:
    - name: install k3s
      include_tasks: tasks/install-k3s.yml

    - name: get ip address
      shell: ip address show eth1 | grep 'inet ' | sed -e 's/^.*inet //' -e 's/\/.*$//'
      register: ip_result

    - name: download the kubeconfig file.
      fetch:
        src: /etc/rancher/k3s/k3s.yaml
        dest: .kubeconfig/
        flat: yes

    - name: replace the ip address in kubeconfig
      replace:
        path: .kubeconfig/k3s.yaml
        regexp: '127.0.0.1'
        replace: "{{ ip_result.stdout }}"
      delegate_to: 127.0.0.1
      become: false

    - name: verify kubectl works from local
      shell: kubectl --kubeconfig=.kubeconfig/k3s.yaml cluster-info
      delegate_to: 127.0.0.1
      become: false
      register: cluster_result_local

    - name: install k8s dashboard
      include_tasks: tasks/install-dashboard.yml

    - name: install nginx app
      kubernetes.core.k8s:
        kubeconfig: /etc/rancher/k3s/k3s.yaml
        state: present
        definition: "{{ item }}"
      loop: "{{ lookup('file', 'k8-configs/app.nginx.yml') | from_yaml_all | list }}"
